default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timezone: 'America/Costa_Rica'

development:
  <<: *default
  database: project_development
  #port: 5433
test:
  <<: *default
  database: project_test
  #port: 5433

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: railwayapp_production
  username: railwayapp
  password: <%= ENV["RAILWAYAPP_DATABASE_PASSWORD"] %>
